# Generated by Django 4.1.1 on 2022-09-18 16:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_date_joined_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('action', models.IntegerField(choices=[(0, 'SIGN UP'), (1, 'LOGIN')], default=1)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('expireAt', models.DateTimeField(default=datetime.datetime(2022, 9, 18, 16, 36, 21, 409215, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
