# Generated by Django 4.1.1 on 2022-09-18 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_sessionotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionotp',
            name='action',
            field=models.IntegerField(choices=[(0, 'SIGN UP'), (1, 'LOGIN'), (2, 'ACTIVATE')], default=1),
        ),
        migrations.AlterField(
            model_name='sessionotp',
            name='expireAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 18, 0, 17, 71986, tzinfo=datetime.timezone.utc)),
        ),
    ]
